In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

Import the data

In [2]:
data_path = './data.csv'
df = pd.read_csv(data_path)


df.head()

1  0.0  0.0.1  -0.0609375  -0.029166666666666667   -0.1125  \
0  1  0.0    0.0   -0.059375              -0.031250 -0.106250   
1  1  0.0    0.0   -0.060937              -0.029167 -0.110937   
2  1  0.0    0.0   -0.060937              -0.031250 -0.109375   
3  1  0.0    0.0   -0.060937              -0.031250 -0.109375   
4  1  0.0    0.0   -0.059375              -0.029167 -0.109375   

   -0.10416666666666667  -0.1453125    -0.175  -0.1703125  ...  -0.0015625  \
0             -0.108333   -0.137500 -0.177083   -0.164062  ...    0.004687   
1             -0.108333   -0.143750 -0.181250   -0.170313  ...    0.000000   
2             -0.110417   -0.140625 -0.177083   -0.167187  ...    0.003125   
3             -0.110417   -0.140625 -0.177083   -0.167187  ...    0.003125   
4             -0.108333   -0.140625 -0.179167   -0.167187  ...    0.000000   

   -0.13541666666666666.1  0.0453125  -0.16875  0.0328125  \
0               -0.139583   0.051562 -0.170833   0.037500   
1               -0.141667   0.046875 -0.175000   0.034375   
2               -0.141667   0.050000 -0.168750   0.037500   
3               -0.141667   0.050000 -0.168750   0.037500   
4               -0.137500   0.048438 -0.170833   0.035937   

   -0.21666666666666667  0.028125  -0.16041666666666668  0.0328125.1  \
0             -0.216667  0.032813             -0.164583     0.039062   
1             -0.218750  0.029687             -0.164583     0.035937   
2             -0.216667  0.032813             -0.164583     0.037500   
3             -0.216667  0.032813             -0.164583     0.037500   
4             -0.216667  0.029687             -0.162500     0.035937   

   -0.14166666666666666  
0             -0.145833  
1             -0.150000  
2             -0.147917  
3             -0.147917  
4             -0.143750  

[5 rows x 43 columns]

In [15]:
print(type(df.iloc[0,1]))
X = np.array(df.iloc[:,1:].values)
Y = np.array(df.iloc[:,0].values)
print(X[10])




<class 'numpy.float64'>
[ 0.          0.         -0.0609375  -0.03125    -0.109375   -0.10833333
 -0.140625   -0.17916667 -0.1671875  -0.22291667 -0.075      -0.17916667
 -0.096875   -0.22916667 -0.0828125  -0.1625     -0.06875    -0.1375
 -0.0359375  -0.18541667 -0.0546875  -0.2375     -0.04375    -0.15625
 -0.0328125  -0.13958333  0.00625    -0.18333333 -0.0078125  -0.24583333
 -0.0046875  -0.16458333  0.003125   -0.14166667  0.0484375  -0.17083333
  0.0375     -0.22083333  0.0328125  -0.16875     0.0375     -0.14791667]
[ 1  1  1 ... 26 26 26]


In [16]:
for i in range(len(Y)):
    if Y[i] <10:
        Y[i] = Y[i] - 1
    else: Y[i] = Y[i] -2

In [17]:
print(Y)

[ 0  0  0 ... 24 24 24]


In [18]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=9)

In [19]:
print(x_train[0])
print(y_train)

[ 0.          0.         -0.084375   -0.06041667 -0.140625   -0.17708333
 -0.1671875  -0.27291667 -0.1875     -0.34583333 -0.0890625  -0.29375
 -0.11875    -0.35416667 -0.115625   -0.25833333 -0.1        -0.20208333
 -0.034375   -0.29583333 -0.0671875  -0.33958333 -0.0640625  -0.225
 -0.0484375  -0.18333333  0.021875   -0.28125    -0.00625    -0.32083333
 -0.009375   -0.21041667  0.003125   -0.15833333  0.078125   -0.26041667
  0.078125   -0.37916667  0.06875    -0.44583333  0.0625     -0.51458333]
[ 8 18 22 ... 10  1  1]


In [20]:
_, features = x_train.shape

In [23]:
labels = ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U'
          'V', 'W', 'X', 'Y', 'Z')

output_size = 25

print(np.min(y_train))

0


In [47]:
model = Sequential()

model.add(Dense(256, activation='relu',input_shape=(42,)))
model.add(Dense(256, activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(features))


In [48]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

model.compile(optimizer=optimizer, 
              loss = SparseCategoricalCrossentropy(from_logits=True), 
              metrics=['accuracy'])

In [43]:
print(np.any(np.isnan(y_test)))


False


In [49]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_23 (Dense)            (None, 256)               11008     
                                                                 
 dense_24 (Dense)            (None, 256)               65792     
                                                                 
 dense_25 (Dense)            (None, 128)               32896     
                                                                 
 dense_26 (Dense)            (None, 128)               16512     
                                                                 
 dense_27 (Dense)            (None, 42)                5418      
                                                                 
Total params: 131,626
Trainable params: 131,626
Non-trainable params: 0
_________________________________________________________________


In [50]:
training_data = model.fit(x_train,y_train,epochs=100,batch_size=16,shuffle=True, validation_data=(x_test,y_test))

Epoch 1/100
220/220 [==============================] - 1s 4ms/step - loss: 1.6954 - accuracy: 0.4512 - val_loss: 0.7924 - val_accuracy: 0.7096
Epoch 2/100
220/220 [==============================] - 1s 3ms/step - loss: 0.6461 - accuracy: 0.7491 - val_loss: 0.4660 - val_accuracy: 0.8189
Epoch 3/100
220/220 [==============================] - 1s 3ms/step - loss: 0.4044 - accuracy: 0.8496 - val_loss: 0.3546 - val_accuracy: 0.8508
Epoch 4/100
220/220 [==============================] - 1s 3ms/step - loss: 0.3184 - accuracy: 0.8784 - val_loss: 0.2691 - val_accuracy: 0.9112
Epoch 5/100
220/220 [==============================] - 1s 3ms/step - loss: 0.2501 - accuracy: 0.9100 - val_loss: 0.2281 - val_accuracy: 0.9294
Epoch 6/100
220/220 [==============================] - 1s 3ms/step - loss: 0.2380 - accuracy: 0.9134 - val_loss: 0.2003 - val_accuracy: 0.9180
Epoch 7/100
220/220 [==============================] - 1s 3ms/step - loss: 0.1655 - accuracy: 0.9399 - val_loss: 0.1364 - val_accuracy: 0.9487

In [51]:
model.save('sign_language_model.h5')